import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Inter } from "next/font/google"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Roboto+Serif:wght@400;700&family=Bebas+Neue&family=Amatic+SC&family=Great+Vibes&family=Concert+One&family=Patua+One&family=Zeyada&family=Courgette&family=Russo+One&family=Silkscreen&family=Gloria+Hallelujah&family=Pacifico&family=Open+Sans:wght@400;700&family=Lato&family=Montserrat:wght@400;700&family=Poppins:wght@400;700&family=Raleway:wght@400;700&family=Merriweather&family=Nunito:wght@400;700&family=Oswald:wght@400;700&family=Source+Sans+Pro:wght@400;700&family=PT+Sans&family=Lora&family=Roboto+Slab:wght@400;700&family=Ubuntu:wght@400;700&family=Playfair+Display:wght@400;700&family=Crimson+Text&family=Libre+Baskerville:wght@400;700&family=Slabo+27px&family=Noto+Sans&family=Rubik:wght@400;700&family=Rubik+Mono+One&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`antialiased h-[100vh] bg-[#F1F2F3] ${inter.className}`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
